### ISSUE TITLE
Theme switching occurs with a delay

### ISSUE THREAD

**Issue by denisgl7** [splashbyte/animated_toggle_switch#47]
https://github.com/splashbyte/animated_toggle_switch/assets/18004353/6e068863-d350-4bad-b30a-bd2e4777d092

When changing the theme, rebuilding will not cause the colors to change immediately

**Comment by maeddin** [comment]
@denisgl7 My current approach is not tested at all. Therefore I would be very happy about your feedback.
There is now the parameter `animateThemeChanges`. Alternatively, you can now set `styleAnimationType` and `indicatorAnimationType` to `AnimationType.none`.
```
animated_toggle_switch:
    git:
      url: https://github.com/SplashByte/animated_toggle_switch.git
      ref: 44-indicator-gradient
```
