### ISSUE TITLE
how do i make it vertical

### ISSUE THREAD

**Issue by shreyas-jadhav** [splashbyte/animated_toggle_switch#61]

**Comment by maeddin** [comment]
Vertical switches are not yet supported, but are already planned.

**Comment by maeddin** [comment]
@shreyas-jadhav Currently you can use `RotatedBox` for rotating your switch and its content:

```
RotatedBox(
   quarterTurns: 1,
   child: AnimatedToggleSwitch(
       iconBuilder: (value) => RotatedBox(quarterTurns: -1, child: ...),
       ...
   ),
)
```

Does this work for you?

**Comment by maeddin** [comment]
I have now added a `vertical()` method to `AnimatedToggleSwitch`. You can use this in your `pubspec.yaml` to test this new feature :

```
animated_toggle_switch:
    git:
      url: https://github.com/splashbyte/animated_toggle_switch.git
      ref: 61-vertical-switch
```
